DROP DATABASE IF EXISTS animedb_one_to_one;
CREATE DATABASE IF NOT EXISTS animedb_one_to_one;
USE animedb_one_to_one;

-- Создаем таблицы со связью с id один к одному
CREATE TABLE IF NOT EXISTS names (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS rates (
    id INT PRIMARY KEY AUTO_INCREMENT,
    episodes INT,
    votes INT,
    rate INT,
    title_id INT,
    FOREIGN KEY (title_id) REFERENCES names(id)
);

INSERT INTO names (title) VALUES
('Naruto'),
('One Piece'),
('Attack on Titan'),
('My Hero Academia'),
('Demon Slayer'),
('Dragon Ball Z'),
('Fullmetal Alchemist'),
('Sword Art Online'),
('Death Note'),
('Tokyo Ghoul'),
('Bleach'),
('Fairy Tail'),
('Hunter x Hunter'),
('One Punch Man'),
('JoJo\'s Bizarre Adventure'),
('Black Clover'),
('Re:Zero'),
('Neon Genesis Evangelion'),
('Steins;Gate'),
('Code Geass'),
('Fate/Stay Night'),
('Overlord'),
('Mob Psycho 100'),
('The Seven Deadly Sins'),
('Gintama'),
('Sword Art Online: Alicization'),
('Naruto: Shippuden'),
('Attack on Titan: Season 2'),
('My Hero Academia: Season 3'),
('Demon Slayer: Mugen Train'),
('Dragon Ball Super'),
('Fullmetal Alchemist: Brotherhood'),
('Sword Art Online II'),
('Death Note: Relight'),
('Tokyo Ghoul:re'),
('Bleach: Thousand-Year Blood War'),
('Fairy Tail: Final Series'),
('Hunter x Hunter: Chimera Ant Arc'),
('One Punch Man: Season 2'),
('JoJo\'s Bizarre Adventure: Golden Wind'),
('Black Clover: Season 2'),
('Re:Zero: Season 2'),
('Neon Genesis Evangelion: The End of Evangelion'),
('Steins;Gate 0'),
('Code Geass: Lelouch of the Rebellion R2'),
('Fate/Stay Night: Unlimited Blade Works'),
('Overlord II'),
('Mob Psycho 100 II'),
('The Seven Deadly Sins: Revival of The Commandments'),
('Gintama: Silver Soul');

INSERT INTO rates (episodes, votes, rate, title_id) VALUES
(220, 350000, 8, (SELECT id FROM names WHERE title = 'Naruto')),
(1000, 500000, 9, (SELECT id FROM names WHERE title = 'One Piece')),
(75, 450000, 9, (SELECT id FROM names WHERE title = 'Attack on Titan')),
(88, 300000, 8, (SELECT id FROM names WHERE title = 'My Hero Academia')),
(26, 400000, 9, (SELECT id FROM names WHERE title = 'Demon Slayer')),
(291, 600000, 8, (SELECT id FROM names WHERE title = 'Dragon Ball Z')),
(64, 420000, 9, (SELECT id FROM names WHERE title = 'Fullmetal Alchemist')),
(25, 380000, 7, (SELECT id FROM names WHERE title = 'Sword Art Online')),
(37, 700000, 9, (SELECT id FROM names WHERE title = 'Death Note')),
(48, 320000, 8, (SELECT id FROM names WHERE title = 'Tokyo Ghoul')),
(366, 300000, 7, (SELECT id FROM names WHERE title = 'Bleach')),
(175, 250000, 7, (SELECT id FROM names WHERE title = 'Fairy Tail')),
(148, 400000, 9, (SELECT id FROM names WHERE title = 'Hunter x Hunter')),
(12, 500000, 8, (SELECT id FROM names WHERE title = 'One Punch Man')),
(152, 200000, 8, (SELECT id FROM names WHERE title = 'JoJo\'s Bizarre Adventure')),
(170, 180000, 7, (SELECT id FROM names WHERE title = 'Black Clover')),
(25, 210000, 8, (SELECT id FROM names WHERE title = 'Re:Zero')),
(26, 300000, 9, (SELECT id FROM names WHERE title = 'Neon Genesis Evangelion')),
(24, 280000, 9, (SELECT id FROM names WHERE title = 'Steins;Gate')),
(50, 260000, 9, (SELECT id FROM names WHERE title = 'Code Geass')),
(24, 230000, 8, (SELECT id FROM names WHERE title = 'Fate/Stay Night')),
(39, 150000, 8, (SELECT id FROM names WHERE title = 'Overlord')),
(25, 220000, 8, (SELECT id FROM names WHERE title = 'Mob Psycho 100')),
(24, 190000, 7, (SELECT id FROM names WHERE title = 'The Seven Deadly Sins')),
(367, 300000, 9, (SELECT id FROM names WHERE title = 'Gintama')),
(47, 170000, 8, (SELECT id FROM names WHERE title = 'Sword Art Online: Alicization')),
(500, 400000, 9, (SELECT id FROM names WHERE title = 'Naruto: Shippuden')),
(12, 320000, 9, (SELECT id FROM names WHERE title = 'Attack on Titan: Season 2')),
(25, 300000, 8, (SELECT id FROM names WHERE title = 'My Hero Academia: Season 3')),
(1, 250000, 10, (SELECT id FROM names WHERE title = 'Demon Slayer: Mugen Train')),
(131, 350000, 7, (SELECT id FROM names WHERE title = 'Dragon Ball Super')),
(64, 420000, 10, (SELECT id FROM names WHERE title = 'Fullmetal Alchemist: Brotherhood')),
(24, 180000, 7, (SELECT id FROM names WHERE title = 'Sword Art Online II')),
(2, 150000, 8, (SELECT id FROM names WHERE title = 'Death Note: Relight')),
(12, 200000, 7, (SELECT id FROM names WHERE title = 'Tokyo Ghoul:re')),
(52, 100000, 8, (SELECT id FROM names WHERE title = 'Bleach: Thousand-Year Blood War')),
(51, 150000, 7, (SELECT id FROM names WHERE title = 'Fairy Tail: Final Series')),
(61, 220000, 9, (SELECT id FROM names WHERE title = 'Hunter x Hunter: Chimera Ant Arc')),
(12, 250000, 7, (SELECT id FROM names WHERE title = 'One Punch Man: Season 2')),
(39, 180000, 8, (SELECT id FROM names WHERE title = 'JoJo\'s Bizarre Adventure: Golden Wind')),
(170, 140000, 7, (SELECT id FROM names WHERE title = 'Black Clover: Season 2')),
(13, 160000, 8, (SELECT id FROM names WHERE title = 'Re:Zero: Season 2')),
(1, 500000, 10, (SELECT id FROM names WHERE title = 'Neon Genesis Evangelion: The End of Evangelion')),
(23, 150000, 8, (SELECT id FROM names WHERE title = 'Steins;Gate 0')),
(25, 280000, 9, (SELECT id FROM names WHERE title = 'Code Geass: Lelouch of the Rebellion R2')),
(12, 130000, 8, (SELECT id FROM names WHERE title = 'Fate/Stay Night: Unlimited Blade Works')),
(13, 140000, 8, (SELECT id FROM names WHERE title = 'Overlord II')),
(13, 160000, 8, (SELECT id FROM names WHERE title = 'Mob Psycho 100 II')),
(24, 150000, 8, (SELECT id FROM names WHERE title = 'The Seven Deadly Sins: Revival of The Commandments')),
(51, 200000, 9, (SELECT id FROM names WHERE title = 'Gintama: Silver Soul'));
